image: node:latest

stages:
  - install
  - build
  - test
  - lint
  - docker-build

cache:
 key: modules
 paths:
  - node_modules/

install:
  stage: install
  artifacts:
    paths:
      - node_modules 
  cache:
    key: modules
    paths:
      - node_modules/
  after_script:
    - node -v && npm -v
  script:
    - npm cache clean --force
    - npm rebuild
    - npm install

build:
  image: node:latest
  stage: build
  cache:
    key: modules
    paths:
      - node_modules/
    policy: pull
  artifacts:
      paths:
        - public
  script:
    - npm run build
    - echo "Build Successfully!"

unit-test:
  image: node:latest
  stage: test
  cache:
    key: modules
    paths:
      - node_modules/
    policy: pull
  script:
    - npm run test:ci
  coverage: /All files[^|]*\|[^|]*\s+([\d\.]+)/
  artifacts:
    paths:
      - coverage/
      - public
    when: always
    reports:
      junit:
        - junit.xml

lint:
  image: node:latest
  stage: lint
  cache:
    key: modules
    paths:
      - node_modules/
    policy: pull
  script:
    - npm run lint
    - echo "All style good!"
  artifacts:
      paths:
        - public

docker-build:
  stage: docker-build
  image: docker:latest
  services:
    - name: docker:dind
      entrypoint: ["env", "-u", "DOCKER_HOST"]
      command: ["dockerd-entrypoint.sh"]
  variables:
    DOCKER_HOST: tcp://docker:2375/
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: ""
  before_script:
    - echo "$CI_REGISTRY"
    - echo $CI_REGISTRY
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY 
  script:
    - docker build --pull -t "$CI_REGISTRY_IMAGE" .
    - docker push "$CI_REGISTRY_IMAGE"
    - echo "Registry image:" $CI_REGISTRY_IMAGE
