image: node:latest

stages:
  - install
  - build
  - test

cache:
 key: modules
 paths:
  - node_modules/

install:modules:
 stage: install
 cache:
  key: modules
  paths:
    - node_modules/
  after_script:
   - node -v && npm -v
  script:
  - npm i

build:
  image: node:latest
  stage: build
  cache:
    key: modules
    paths:
      - node_modules/
    policy: pull
  script:
    - npm run build
    - echo "Build Successfully!"

unit-test:
  image: node:latest
  stage: test
  cache:
    key: modules
    paths:
      - node_modules/
    policy: pull
  script:
    - npm run test:ci
  coverage: /All files[^|]*\|[^|]*\s+([\d\.]+)/
  artifacts:
    paths:
      - coverage/
    when: always
    reports:
      junit:
        - junit.xml