image: node:latest

stages:
  - install
  - build
  - test
  - lint

cache:
 key: modules
 paths:
  - node_modules/

install:
  stage: install
  cache:
    key: modules
    paths:
      - node_modules/
  after_script:
    - node -v && npm -v
  script:
    - npm install

build:
  image: node:latest
  stage: build
  cache:
    key: modules
    paths:
      - node_modules/
    policy: pull
  script:
    - npm run build
    - echo "Build Successfully!"

unit-test:
  image: node:latest
  stage: test
  cache:
    key: modules
    paths:
      - node_modules/
    policy: pull
  script:
    - npm run test:ci
  coverage: /All files[^|]*\|[^|]*\s+([\d\.]+)/
  artifacts:
    paths:
      - coverage/
    when: always
    reports:
      junit:
        - junit.xml

lint:
  image: node:latest
  stage: lint
    cache:
    key: modules
    paths:
      - node_modules/
    policy: pull
  script:
    - npm runt lint
    - echo "All style good!"