image: node:latest

stages:
  - install
  - build
  - lint
  - deploy

cache:
 key: modules
 paths:
  - node_modules/

install:
  stage: install
  artifacts:
    paths:
      - node_modules 
  cache:
    key: modules
    paths:
      - node_modules/
  after_script:
    - node -v && npm -v
  script:
    - npm cache clean --force
    - npm rebuild
    - npm install

build:
  image: node:latest
  stage: build
  cache:
    key: modules
    paths:
      - node_modules/
    policy: pull
  artifacts:
      paths:
        - public
  script:
    - npm run build
    - echo "Build Successfully!"

lint:
  image: node:latest
  stage: lint
  cache:
    key: modules
    paths:
      - node_modules/
    policy: pull
  script:
    - npm run lint
    - echo "All style good!"
  artifacts:
      paths:
        - public

deploy:
  only:
    - master
  stage: deploy
  script:
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl
    - dpl --provider=heroku --app=challenger --api-key=$HEROKU_TOKEN
